version: '3'
services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Maps port 8000 on the container to port 8000 on the host
    volumes:
      - .:/MainApi  # Mount the current directory to /app inside the container
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    
